services:
  rabbitmq:
    image: library/rabbitmq:3-management
    container_name: estudomq
    volumes:
    - ./.docker/estudomq/etc/:/etc/estudomq/
    - ./.docker/estudomq/var/:/var/estudomq/
    - ./.docker/estudomq/log/:/log/estudomq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
    - 5672:5672
    - 15672:15672